name = "PairsMacros"
uuid = "a3ed533e-75b3-46cb-ad8a-82d33aefb744"
version = "0.2.0"

[deps]

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[targets]
test = ["Test", "DataFrames"]
