name = "DataFramesMacro"
uuid = "a3ed533e-75b3-46cb-ad8a-82d33aefb744"
authors = ["matthieugomez <gomez.matthieu@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "324d7699-5711-5eae-9e2f-1d82baa6b597"

[compat]
julia = "1"
DataFrames = "0.21"